version: 0.2
phases:
  install:
    commands:
      - ls -la
      - chmod +x pipeline/build.sh
      - ./pipeline/build.sh
artifacts:
  type: zip
  files:
    - "**/*"
  base-directory: /tmp/packaged
